config/routes.rb
Rails.application.routes.draw do
  root to: 'graphs#index'
  get 'optimizations', to: 'optimizations#index'
  resources :edges
  resources :nodes
  resources :optimizations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/edge.rb
class Edge < ApplicationRecord
end

app/models/node.rb
class Node < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/edges_controller.rb
class EdgesController < ApplicationController
  before_action :set_edge, only: [:show, :edit, :update, :destroy]

  # GET /edges
  # GET /edges.json
  def index
    @edges = Edge.all
  end

  # GET /edges/1
  # GET /edges/1.json
  def show
  end

  # GET /edges/new
  def new
    @edge = Edge.new
    @nodes = Node.all
    @array = []
    @nodes.each do |node|
      @array << [node.name, node.name]
    end
  end

  # GET /edges/1/edit
  def edit
  end

  # POST /edges
  # POST /edges.json
  def create
    @edge = Edge.new(edge_params)
    @nodes = Node.all

    respond_to do |format|
      if @edge.save
        format.html { redirect_to @edge, notice: 'Edge was successfully created.' }
        format.json { render :show, status: :created, location: @edge }
      else
        format.html { render :new }
        format.json { render json: @edge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edges/1
  # PATCH/PUT /edges/1.json
  def update
    respond_to do |format|
      if @edge.update(edge_params)
        format.html { redirect_to @edge, notice: 'Edge was successfully updated.' }
        format.json { render :show, status: :ok, location: @edge }
      else
        format.html { render :edit }
        format.json { render json: @edge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edges/1
  # DELETE /edges/1.json
  def destroy
    @edge.destroy
    respond_to do |format|
      format.html { redirect_to edges_url, notice: 'Edge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edge
      @edge = Edge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def edge_params
      params.require(:edge).permit(:name, :source, :destiny, :value)
    end
end

app/controllers/graphs_controller.rb
require 'rgl/adjacency'
require 'rgl/dot'
require 'rgl/traversal'
require 'rgl/dijkstra'
require 'rgl/base'
require 'rgl/graph_visitor'
require 'rgl/dijkstra_visitor'
require 'rgl/edge_properties_map'
require 'rgl/path_builder'
require 'lazy_priority_queue'

class GraphsController < ApplicationController
  def index
    @graph = GraphBuilder.call
    @graph.write_to_graphic_file('jpg', 'public/graph2')  #tem como colocar cores
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  # GET /nodes/1
  # GET /nodes/1.json
  def show
  end

  # GET /nodes/new
  def new
    @node = Node.new
  end

  # GET /nodes/1/edit
  def edit
  end

  # POST /nodes
  # POST /nodes.json
  def create
    @node = Node.new(node_params)

    respond_to do |format|
      if @node.save
        format.html { redirect_to @node, notice: 'Node was successfully created.' }
        format.json { render :show, status: :created, location: @node }
      else
        format.html { render :new }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nodes/1
  # PATCH/PUT /nodes/1.json
  def update
    respond_to do |format|
      if @node.update(node_params)
        format.html { redirect_to @node, notice: 'Node was successfully updated.' }
        format.json { render :show, status: :ok, location: @node }
      else
        format.html { render :edit }
        format.json { render json: @node.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nodes/1
  # DELETE /nodes/1.json
  def destroy
    @node.destroy
    respond_to do |format|
      format.html { redirect_to nodes_url, notice: 'Node was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_node
      @node = Node.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def node_params
      params.require(:node).permit(:name, :value)
    end
end

app/controllers/optimizations_controller.rb
class OptimizationsController < ApplicationController

    # o mesmo grafo feito no controller vai vir pra ca?

  def index
    @dijkstra = Optimizations.dijkstra_shortest_paths(GraphBuilder.call, GraphBuilder.edge_values)
    @bellman_ford = Optimizations.bellman_ford_shortest_paths(GraphBuilder.call, GraphBuilder.edge_values)
    @prim_tree = Optimizations.prim_minimum_spanning_tree(GraphBuilder.call, GraphBuilder.edge_values)
    @prim_cost = Optimizations.prim_cost(@prim_tree.edges)
    @graph = TreeBuilder.call(@prim_tree.edges)
    @graph.write_to_graphic_file('jpg', 'public/tree')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/edge_helper.rb
module EdgeHelper
end

app/helpers/edges_helper.rb
module EdgesHelper
end

app/helpers/graph_helper.rb
module GraphHelper
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/helpers/optimizations_helper.rb
module OptimizationsHelper
end

app/helpers/route_helper.rb
module RouteHelper
end

app/views/edges/_form.html.erb
<%= form_with(model: edge, local: true) do |form| %>
  <% if edge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(edge.errors.count, "error") %> prohibited this edge from being saved:</h2>

      <ul>
        <% edge.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <br>

  <div class="row">
      <div class="col-sm-2">
          <div class="form-group">
              <%= form.label :source %>
              <%= form.text_field :source %>
          </div>
      </div>
  </div>
  <br>

    <div class="row">
      <div class="col-sm-2">
          <div class="form-group">
              <%= form.label :destiny %>
              <%= form.text_field :destiny %>
          </div>  
      </div>
  </div>
  <br>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
  <br>
<%end%>

app/views/edges/edit.html.erb
<h1>Editing Edge</h1>

<%= render 'form', edge: @edge %>

<%= link_to 'Show', @edge, class: "btn btn-success btn-sm" %> |
<%= link_to 'Back', edges_path, class: "btn btn-default btn-sm" %>

app/views/edges/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box2">
  <h3>Edges<h3>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th><h4>Name</h4></th>
      <th><h4>Source</h4></th>
      <th><h4>Destiny</h4></th>
      <th><h4>Value</h4></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @edges.each do |edge| %>
      <tr>
        <td><h4><%= edge.name %></h4></td>
        <td><h4><%= edge.source %></h4></td>
        <td><h4><%= edge.destiny %></h4></td>
        <td><h4><%= edge.value %></h4></td>
        <td><%= link_to 'Destroy', edge, method: :delete, class: "btn btn-danger btn-sm", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Edge', new_edge_path, class: "btn btn-default btn-sm" %>
<br>
<br>

app/views/edges/new.html.erb
<h3>New Edge</h3>
<br>

<%= render 'form', edge: @edge %>


<%= link_to 'Back', edges_path, class: "btn btn-default btn-sm" %>
<br>
<br>

app/views/edges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @edge.name %>
</p>

<p>
  <strong>Source:</strong>
  <%= @edge.source %>
</p>

<p>
  <strong>Destiny:</strong>
  <%= @edge.destiny %>
</p>

<p>
  <strong>Value:</strong>
  <%= @edge.value %>
</p>

<%= link_to 'Edit', edit_edge_path(@edge), class: "btn btn-warning btn-sm"%> |
<%= link_to 'Back', edges_path, class: "btn btn-default btn-sm" %>

app/views/graphs/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <h3>Graph<h3><p>
</div>

<tbody>
  <img src= "graph2.jpg"/>
</tbody>

<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoutingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  </head>
  
  <body>
      <%= nav_bar brand: "Graph", class:"navbar navbar-expand-lg", brand_link: root_url do %>
        <%= menu_group do %>
        <%= menu_item "Nodes", nodes_path %>
        <%= menu_item "Edges", edges_path %>
        <%= menu_item "Route Optimizations",  optimizations_path %>
        <%end%>
      <%end%>
      
    <div class="container container-form">
      <%= yield %>
    </div>
  </body>
</html>

app/views/nodes/_form.html.erb
<%= form_with(model: node, local: true) do |form| %>
  <% if node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
        <% node.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <br>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>
  <br>

  <div class="actions">
    <%= form.submit %>
  </div>
  <br>
<% end %>

app/views/nodes/edit.html.erb
<h1>Editing Node</h1>

<%= render 'form', node: @node %>

<%= link_to 'Show', @node, class: "btn btn-success btn-sm" %> 
<%= link_to 'Back', nodes_path, class: "btn btn-default btn-sm" %>

app/views/nodes/index.html.erb
<p id="notice"><%= notice %></p>

<div class="box2">
  <h3>Nodes<h3><p>
</div>


<table class="table table-striped">
  <thead>
    <tr>
      <th><h4>Name</h4></th>
      <th><h4>Value</h4></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nodes.each do |node| %>
      <tr>
        <td><h4><%= node.name %></h4></td>
        <td><h4><%= node.value %></h4></td>
        <td><%= link_to 'Destroy', node, method: :delete, class: "btn btn-danger btn-sm" , data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Node', new_node_path, class: "btn btn-default btn-sm" %>
<br>
<br>

app/views/nodes/new.html.erb
<h3>New Node</h3>
<br>

<%= render 'form', node: @node %>

<%= link_to 'Back', nodes_path, class: "btn btn-default btn-sm" %>
<br>
<br>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @node.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @node.value %>
</p>

<%= link_to 'Edit', edit_node_path(@node), class: "btn btn-warning btn-sm" %> |
<%= link_to 'Back', nodes_path, class: "btn btn-default btn-sm" %>

app/views/optimizations/index.html.erb
  <% if flash[:notice]%>
    <div class="alert alert-success" role="alert">
        <%= flash[:notice] %>
    </div>
<%end%>

<tbody>
    <div class="box2">
    <h3>Prim Minimum Tree:</h3>
    <h4><%=@prim_tree%></h4>
    <br>
    <br>
  </div>
    <div class="box2">
    <h3>Prim Minimum Tree Cost:</h3>
    <h4><%=@prim_cost%></h4>
    <br>
    <br>
  </div>
  <img src= "tree.jpg"/>
</tbody>